package com.desarrollodroide.pagekeeper.di

import android.content.Context
import android.util.Log
import coil3.ImageLoader
import coil3.disk.DiskCache
import coil3.network.cachecontrol.CacheControlCacheStrategy
import coil3.network.okhttp.OkHttpNetworkFetcherFactory
import okhttp3.OkHttpClient
import okhttp3.Response
import okio.Path.Companion.toOkioPath
import java.io.File

private const val IMAGE_CACHE_DIR = "image_cache"
private const val IMAGE_CACHE_MAX_BYTES = 250L * 1024 * 1024

/** A year. Only ever applied to responses that say nothing about caching themselves. */
private const val FALLBACK_CACHE_CONTROL = "public, max-age=31536000"

/**
 * The app's image pipeline.
 *
 * Lives here rather than inline in the Koin module so a test can exercise the real configuration
 * instead of a copy of it that drifts.
 */
fun buildImageLoader(
    context: Context,
    cacheDirectory: File = context.cacheDir.resolve(IMAGE_CACHE_DIR),
): ImageLoader = ImageLoader.Builder(context)
    // coil3 has no okHttpClient {}. The network layer is a fetcher component, and the
    // okhttp one has to be added explicitly or nothing over http loads at all.
    .components {
        add(OkHttpNetworkFetcherFactory(
            // Coil's default strategy serves whatever is in the disk cache without looking at the
            // response's caching headers, so it never revalidates and never sends If-None-Match.
            // Shiori answers a matching If-None-Match on thumbnails with a 304, and its ETag
            // carries the bookmark's modified date, so this is what lets an updated thumbnail
            // appear at all.
            cacheStrategy = { CacheControlCacheStrategy() },
            callFactory = {
            OkHttpClient.Builder()
                .retryOnConnectionFailure(true)
                .addInterceptor { chain ->
                    val response = chain.proceed(chain.request())
                    if (response.code >= 400) {
                        Log.e("BookmarkImageView", "HTTP error: ${response.code}")
                    }
                    applyFallbackCacheControl(response)
                }
                .build()
        }))
    }
    .diskCache {
        DiskCache.Builder()
            // okio Path, not File.
            .directory(cacheDirectory.toOkioPath())
            .maxSizeBytes(IMAGE_CACHE_MAX_BYTES)
            .build()
    }
    .build()

/**
 * Gives a response a long cache lifetime, but only when the server expressed no opinion.
 *
 * This used to rewrite `Cache-Control` on every response to a year, unconditionally. Shiori serves
 * thumbnails with `no-cache, must-revalidate` plus an `ETag` built from the bookmark's modified
 * date, precisely so a client revalidates and gets a cheap 304 while still noticing a change. The
 * blanket override threw that away: nothing ever revalidated, no `If-None-Match` was ever sent, and
 * a thumbnail regenerated by "update cache" would not appear for a year.
 *
 * Responses that carry no caching hints at all still get the long lifetime, which is what the
 * override was presumably reaching for.
 */
internal fun applyFallbackCacheControl(response: Response): Response {
    val serverSaidSomething = response.header("Cache-Control") != null ||
        response.header("ETag") != null ||
        response.header("Last-Modified") != null

    return if (serverSaidSomething) {
        response
    } else {
        response.newBuilder().header("Cache-Control", FALLBACK_CACHE_CONTROL).build()
    }
}
