package com.desarrollodroide.pagekeeper.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006B5E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF76F8E1)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF4A635E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE8E1)
val md_theme_light_onSecondaryContainer = Color(0xFF06201B)
val md_theme_light_tertiary = Color(0xFF446279)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCAE6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E30)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFA)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFDFA)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EF)
val md_theme_light_inverseSurface = Color(0xFF2D3130)
val md_theme_light_inversePrimary = Color(0xFF56DBC5)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006B5E)
val md_theme_light_outlineVariant = Color(0xFFBEC9C5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF56DBC5)
val md_theme_dark_onPrimary = Color(0xFF003730)
val md_theme_dark_primaryContainer = Color(0xFF005046)
val md_theme_dark_onPrimaryContainer = Color(0xFF76F8E1)
val md_theme_dark_secondary = Color(0xFFB1CCC5)
val md_theme_dark_onSecondary = Color(0xFF1C3530)
val md_theme_dark_secondaryContainer = Color(0xFF334B46)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8E1)
val md_theme_dark_tertiary = Color(0xFFACCAE5)
val md_theme_dark_onTertiary = Color(0xFF133348)
val md_theme_dark_tertiaryContainer = Color(0xFF2C4A60)
val md_theme_dark_onTertiaryContainer = Color(0xFFCAE6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE0E3E1)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE0E3E1)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_outline = Color(0xFF899390)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E1)
val md_theme_dark_inversePrimary = Color(0xFF006B5E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF56DBC5)
val md_theme_dark_outlineVariant = Color(0xFF3F4946)
val md_theme_dark_scrim = Color(0xFF000000)


// Surface container tones.
// M3 (and Expressive especially) expresses depth with tonal surfaces rather than shadows, so the
// neutral ramp below is what cards, sheets and bars sit on. Without these roles every elevated
// container falls back to `surface` and the whole screen reads flat.
val md_theme_light_surfaceDim = Color(0xFFDADDDA)
val md_theme_light_surfaceBright = Color(0xFFFAFDFA)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF1F4F1)
val md_theme_light_surfaceContainer = Color(0xFFEBEEEB)
val md_theme_light_surfaceContainerHigh = Color(0xFFE8EBE9)
val md_theme_light_surfaceContainerHighest = Color(0xFFE2E6E3)

// Each step must be visibly lighter than `surface` (0xFF191C1B) or containers disappear into the
// background in dark mode — surfaceContainerLow starts *above* surface, not level with it.
val md_theme_dark_surfaceDim = Color(0xFF111413)
val md_theme_dark_surfaceBright = Color(0xFF373B3A)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0F1211)
val md_theme_dark_surfaceContainerLow = Color(0xFF1E2221)
val md_theme_dark_surfaceContainer = Color(0xFF232726)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2D3130)
val md_theme_dark_surfaceContainerHighest = Color(0xFF383C3B)

val seed = Color(0xFF00584D)


